version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: agentverse_api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
