server {
    listen 80;
    
    location /api/commander/ {
        proxy_pass http://commander:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/workflow/ {
        proxy_pass http://workflow:8103/api/workflow/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/memory/ {
        proxy_pass http://memory:8102/api/memory/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/communication/ {
        proxy_pass http://communication:8104/api/communication/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
